### ISSUE TITLE
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView

### ISSUE THREAD

**Issue by parcool** [Esri/arcgis-runtime-samples-android#268]
As the title,when i use mapview in fragment not in activity,it caused!the difference is it was load by LayoutInflater just like `    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        if (mView == null) {
            mView = inflater.inflate(R.layout.fragment_unit, container, false);
            initViews();
            initMap();
        }
        return mView;
    }`
all the logcat info:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{android.zhixun.uiho.com.gissystem/android.zhixun.uiho.com.gissystem.ui.activity.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView
at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
at android.zhixun.uiho.com.gissystem.ui.fragment.UnitFragment.onCreateView(UnitFragment.java:43)
at android.app.Fragment.performCreateView(Fragment.java:2220)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentController.execPendingActions(FragmentController.java:325)
at android.app.Activity.performStart(Activity.java:6252)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
... 9 more
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView
at android.view.LayoutInflater.createView(LayoutInflater.java:645)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
... 19 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at android.view.LayoutInflater.createView(LayoutInflater.java:619)
... 24 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/android.zhixun.uiho.com.gissystem-2/base.apk"],nativeLibraryDirectories=[/data/app/android.zhixun.uiho.com.gissystem-2/lib/x86_64, /data/app/android.zhixun.uiho.com.gissystem-2/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libruntimecore_java.so"
at java.lang.Runtime.loadLibrary(Runtime.java:367)
at java.lang.System.loadLibrary(System.java:1076)
java.lang.RuntimeException: Unable to start activity ComponentInfo{android.zhixun.uiho.com.gissystem/android.zhixun.uiho.com.gissystem.ui.activity.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-30 03:57:44.618 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.zhixun.uiho.com.gissystem.ui.fragment.UnitFragment.onCreateView(UnitFragment.java:43)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.Fragment.performCreateView(Fragment.java:2220)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:793)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.FragmentController.execPendingActions(FragmentController.java:325)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.Activity.performStart(Activity.java:6252)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: 	... 9 more
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.esri.arcgisruntime.mapping.view.MapView
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
11-30 03:57:44.619 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: 	... 19 more
11-30 03:57:44.621 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: Caused by: java.lang.reflect.InvocationTargetException
11-30 03:57:44.630 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
11-30 03:57:44.630 5907-5907/android.zhixun.uiho.com.gissystem W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
11-30 03:57:44.630 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: 	... 24 more
11-30 03:57:44.630 5907-5907/android.zhixun.uiho.com.gissystem W/System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/android.zhixun.uiho.com.gissystem-2/base.apk"],nativeLibraryDirectories=[/data/app/android.zhixun.uiho.com.gissystem-2/lib/x86_64, /data/app/android.zhixun.uiho.com.gissystem-2/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libruntimecore_java.so"
at java.lang.Runtime.loadLibrary(Runtime.java:367)
at java.lang.System.loadLibrary(System.java:1076)
at com.esri.arcgisruntime.ArcGISRuntimeEnvironment.a(SourceFile:183)
at com.esri.arcgisruntime.ArcGISRuntimeEnvironment.initialize(SourceFile:162)
at com.esri.arcgisruntime.internal.jni.CoreDevice.<clinit>(SourceFile:35)
at com.esri.arcgisruntime.mapping.view.MapView.<init>(SourceFile:331)
... 26 moreat com.esri.arcgisruntime.ArcGISRuntimeEnvironment.a(SourceFile:183)
at com.esri.arcgisruntime.ArcGISRuntimeEnvironment.initialize(SourceFile:162)
at com.esri.arcgisruntime.internal.jni.CoreDevice.<clinit>(SourceFile:35)
at com.esri.arcgisruntime.mapping.view.MapView.<init>(SourceFile:331)
... 26 more`

but XiaoMi Note(6.0.1) runs well and Samsung galaxy s7 edge(6.0.1) crashed!

**Comment by doneill** [comment]
@parcool Is your issue with a specific sample?  Please cite the specific sample so we can investigate.

**Comment by parcool** [comment]
not in a specific sample in your samples.i will upload my sample to github and paste the url here!

**Comment by parcool** [comment]
finally,i find the reason,because i add fresco in the app gradle file,if i remove it ,it runs well! [see my test project](https://github.com/parcool/Test01).but i don't know why?

**Comment by doneill** [comment]
I will investigate and report here if I find something.

**Comment by Brislis** [comment]
please add 
 defaultConfig {
     applicationId "com.xxx.xxx" 
     ......
     ndk {
         abiFilters 'armeabi', 'armeabi-v7a', 'armeabi-v8a' 
     }
     ......
 }
in your build.gradle(moudle:app);
but i do not why.

**Comment by sshahidaslamm** [comment]
For Android Studio 3.0.1

I have got the same issue and I have resolved finally Opening the `gradle.properties` and added following line:

`android.enableAapt2=false`

**Comment by resitamas** [comment]
I have the same problem with an Android 7.0 Samsung Galaxy S8 Edge (Samsung Galaxy S8 64GB G950F) device. 

@Brislis if i add those _abiFilters_ than no map appears

@sshahidaslamm ```android.enableAapt2=false``` will soon be deprecated

Is there any other solution now?

**Comment by LuckyMadu** [comment]
I am facing the same issue
![Screenshot 2022-11-25 at 22 31 20](https://user-images.githubusercontent.com/19740478/204033011-51b99746-709b-49e0-8f8a-8ea94ca631fb.png)
