### ISSUE TITLE
Error is EGL_BAD_CONFIG

### ISSUE THREAD

**Issue by Morcal** [Esri/arcgis-runtime-samples-android#307]
04-19 19:49:54.948 11422-11462/com.esri.arcgisruntime.sample.displaydevicelocation E/AndroidRuntime: FATAL EXCEPTION: GLThread 561
                                                                                                     Process: com.esri.arcgisruntime.sample.displaydevicelocation, PID: 11422
                                                                                                     java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
                                                                                                         at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1233)
                                                                                                         at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1224)
                                                                                                         at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1074)
                                                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1447)
                                                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by doneill** [comment]
@Morcal Can you provide any more context?  Did you just fork/clone sample and run it?  If so, what device/emulator are you running it on?

**Comment by urbutisj** [comment]
Same problem

**Comment by doneill** [comment]
@urbutisj Do you have more context to share?  How are you reproducing the issue?

**Comment by urbutisj** [comment]
https://geonet.esri.com/message/691486-eglbadconfig I wrote question on Geonet.

**Comment by zxklovetml** [comment]
Same problem

**Comment by Pinggo** [comment]
same problem ---arcgis 100.1
