### ISSUE TITLE
No resource identifier found for attribute 'roundIcon' in package 'android'

### ISSUE THREAD

**Issue by JavaBoyHW** [Esri/arcgis-runtime-samples-android#410]
I have dowload the : "arcgis-runtime-samples-android.zip",then I decompression the arcgis-runtime-samples-android.zip, then in the Android Studio ：File -> Open。
The gradle finished with 3error in55s。
The error is ：
No resource identifier found for attribute 'roundIcon' in package 'android'
No resource identifier found for attribute 'roundIcon' in package 'android'
Execution failed for task ':attribution-view-change:processDebugResources'.
>com.android.ide.common.process.ProcessException:Failed to execute aapt

**Comment by TADraeseke** [comment]
Hi JavaBoy,

While we normally recommend cloning rather than downloading the samples as a .zip, downloading as a zip should work fine.

Here's what I just did:

Downloaded .zip file and unzip it.

Open Android Studio and Click 'Import Project'

Select the folder 'arcgis-runtime-samples-android-master'

Let gradle run (will take 1+ minutes depending on the specs of your computer).

Should be good to go. (This was on Android Studio 2.3.3 by the way)

**Comment by ouihamdaoui** [comment]
Log For : app.apk 

 Log Type : Recompiling 

 Log Recorded At : 12 2018-01- 1:45:14,62 

 Log Recorded By : Advanced ApkTool v4.2.0 By BDFreak 

------------------------------------------------------ 

W: C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml:17: error: No resource identifier found for attribute 'roundIcon' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_2398306806873326291.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL1461790945806678721.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_2398306806873326291.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL1461790945806678721.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_2398306806873326291.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL1461790945806678721.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more

------------------------------------------------------
