### ISSUE TITLE
GeoPackage.gpkg文件字段类型为DataTime写入时报错 Abort due to constraint violation

### ISSUE THREAD

**Issue by chunxueer** [Esri/arcgis-runtime-samples-android#475]
## GeoPackage.gpkg文件字段类型为DataTime写入时报错 Abort due to constraint violation
您好：
1、当我加载GeoPackageFeatureTable数据时，数据类型为DatatTime，设置值时报错，而使用GeodatabaseFeatureTable或者ShapefileFeatureTable时正常。
2、加载的GeoPackage.gpkg文件中的数据，是在arcgis desktop 10.4 中创建，并导入的shp文件。
3、 能否告知时间操作的正确方式，非常感谢！

**运行环境为:**  `com.esri.arcgisruntime:arcgis-android:100.2.1、android 7.1`

**相关代码：** 
`
GregorianCalendar gregorianCalendar =new GregorianCalendar();
gregorianCalendar.setTime(new Date());
feature.getAttributes().put("CREATETIME", gregorianCalendar);
...

 ListenableFuture<Void> result = geotable.addFeatureAsync(feature);
 result.addDoneListener(new Runnable() {
  @Override
  public void run() { 
     try {
         result.get();
     } catch (Exception es) {
        Log.e(TAG, "",es );
     }
  }
 });
`

**错误信息：**
java.util.concurrent.ExecutionException: com.esri.arcgisruntime.ArcGISRuntimeException: Abort due to constraint violation
at com.esri.arcgisruntime.internal.a.b.get(SourceFile:128)
at com.ovit.app.map.custom.MapHelper$4.run(MapHelper.java:494)
at com.esri.arcgisruntime.internal.a.g.b(SourceFile:45)
at com.esri.arcgisruntime.internal.a.e.a(SourceFile:115)
at com.esri.arcgisruntime.internal.a.b.a(SourceFile:174)
at com.esri.arcgisruntime.internal.a.b.a(SourceFile:46)
at com.esri.arcgisruntime.internal.a.b$1.a(SourceFile:53)
at com.esri.arcgisruntime.internal.jni.CoreTask.onTaskCompleted(SourceFile:144)
 Caused by: com.esri.arcgisruntime.ArcGISRuntimeException: Abort due to constraint violation
at com.esri.arcgisruntime.internal.a.b.get(SourceFile:120)
at com.ovit.app.map.custom.MapHelper$4.run(MapHelper.java:494) 
at com.esri.arcgisruntime.internal.a.g.b(SourceFile:45) 
at com.esri.arcgisruntime.internal.a.e.a(SourceFile:115) 
at com.esri.arcgisruntime.internal.a.b.a(SourceFile:174) 
at com.esri.arcgisruntime.internal.a.b.a(SourceFile:46) 
at com.esri.arcgisruntime.internal.a.b$1.a(SourceFile:53) 
at com.esri.arcgisruntime.internal.jni.CoreTask.onTaskCompleted(SourceFile:144)

**Comment by pengfei666** [comment]
翻译成英文提issue吧。这帮子人看不懂中文

**Comment by changanxian** [comment]
你的问题正在调研， 请以后使用 https://community.esri.com/ 网站报告问题， 谢谢！
